steps:
- name: 'gcr.io/fastlaneci/firebasebuildstep:latest'
  args: [--build_id=$BUILD_ID --build_env=autopush]
  dir: '/fastlane.ci'
artifacts:
  objects:
    location: 'gs://firebase_build_artifacts/$BUILD_ID/'
    paths: ['/workspace/artifacts-$BUILD_ID.tgz']
logsBucket: firebase_build_artifacts

